version: '3'
services:
  auto_deploy:
    # build needs access to app/, so we'll just build in current directory
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - COMMAND=cd /app/ghlabel_bot && /deploy/pull_and_deploy.sh
        - CRON=* * * * *
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock   # docker socket
    - /root/:/app
    - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa  # ssh key